services:
  java-appA:
    image: maiwalsh/hello-world-java-a:latest
    container_name: hello-world-java-a
    restart: unless-stopped
  
  java-appB:
    image: maiwalsh/hello-world-java-b:latest
    container_name: hello-world-java-b
    restart: unless-stopped
