services:
  producer:
    build:
      context: ./Hello-World-JavaA
    container_name: producer
    depends_on:
      - broker
    networks:
    - traefik
    - confluent
    environment:
      KAFKA_BROKER: "broker:29092"
    restart: unless-stopped

  consumer:
    build:
      context: ./Hello-World-JavaB
    container_name: consumer
    depends_on:
      - broker
    networks:
    - traefik
    - confluent
    environment:
      KAFKA_BROKER: "broker:29092"
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
  confluent:
    name: confluent
    external: true