services:
  producer:
    # build:
      # context: ./Java-Producer
    image: maiwalsh/java-hb-producer:latest
    container_name: producer
    networks:
    - traefik
    - confluent
    environment:
      KAFKA_BROKER: "confluent-broker.recrocog.com:9092"
    restart: unless-stopped

  consumer:
    # build:
      # context: ./Java-Consumer
    image: maiwalsh/java-consumer:latest
    container_name: consumer
    networks:
    - traefik
    - confluent
    environment:
      KAFKA_BROKER: "confluent-broker.recrocog.com:9092"
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
  confluent:
    name: confluent_confluent
    external: true
